/**  Cart */
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_TO_CART'
export const MOVE_TO_WISHLIST = 'MOVE_TO_WISHLIST'
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY '


export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
export const MOVE_TO_CART = 'MOVE_TO_CART'
export const REMOVE_FROM_WISHLIST = 'REMOVE_TO_WISHLIST'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'
